[colors]
foreground = "#8a9cc2"
background = "#161617"
cursor_bg = "#8a9cc2"
cursor_border = "#8a9cc2"
cursor_fg = "#161617"
selection_bg = "#26314e"
selection_fg = "#8a9cc2"
split = "#7aa2f7"
compose_cursor = "#e5b799"
scrollbar_thumb = "#292e42"

ansi = ["#0f0f10", "#f38ba8", "#b4cea1", "#f9e2af", "#7aa2f7", "#cba6f7", "#7dcfff", "#a9b1d6"]
brights = ["#414868", "#ff9ab6", "#b5e191", "#fef1d7", "#8db0ff", "#d6b6ff", "#a4daff", "#8a9cc2"]

[colors.tab_bar]
inactive_tab_edge = "#131314"
background = "#161617"

[colors.tab_bar.active_tab]
fg_color = "#131314"
bg_color = "#7aa2f7"

[colors.tab_bar.inactive_tab]
fg_color = "#6c7086"
bg_color = "#292e42"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#7aa2f7"
bg_color = "#292e42"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#7aa2f7"
bg_color = "#161617"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#7aa2f7"
bg_color = "#161617"

[metadata]
aliases = []
author = "folke"
name = "kyotonight_old"