# -----------------------------------------------------------------------------
# kyotonight Alacritty Colors
# Theme: kyoto Nightold
# Upstream: https://github.com/folke/kyotonight.nvim/raw/main/extras/alacritty/kyotonight_old.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#161617'
foreground = '#8a9cc2'

#[colors.cursor]
#cursor = '#8a9cc2'
#text = '#161617'

# Normal colors
[colors.normal]
black = '#0f0f10'
red = '#f38ba8'
green = '#b4cea1'
yellow = '#f9e2af'
blue = '#7aa2f7'
magenta = '#cba6f7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff9ab6'
green = '#b5e191'
yellow = '#fef1d7'
blue = '#8db0ff'
magenta = '#d6b6ff'
cyan = '#a4daff'
white = '#8a9cc2'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#e5b799'

[[colors.indexed_colors]]
index = 17
color = '#eba0ac'

