# -----------------------------------------------------------------------------
# kyotonight Alacritty Colors
# Theme: kyoto Night
# Upstream: https://github.com/folke/kyotonight.nvim/raw/main/extras/alacritty/kyotonight_simple.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#12131b'
red = '#f38ba8'
green = '#b4cea1'
yellow = '#f9e2af'
blue = '#8a9cc2'
magenta = '#cba6f7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff9ab6'
green = '#b5e191'
yellow = '#fef1d7'
blue = '#91a9db'
magenta = '#d6b6ff'
cyan = '#a4daff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#e5b799'

[[colors.indexed_colors]]
index = 17
color = '#eba0ac'

