[[themes]]
name = "kyoto Nightold"
[themes.palette]
background = "#131314"
foreground = "#a9b1d6"
black = "#414868"
red = "#f38ba8"
green = "#b4cea1"
yellow = "#f9e2af"
blue = "#7aa2f7"
magenta = "#cba6f7"
cyan = "#7dcfff"
white = "${white}"
bright_black = "#161617"
bright_red = "#eba0ac"
bright_green = "#addad7"
bright_yellow = "#e5b799"
bright_blue = "#7aa2f7"
bright_magenta = "#e91f70"
bright_cyan = "#0db9d7"
bright_white = "#8a9cc2"
