[[themes]]
name = "kyoto Night"
[themes.palette]
background = "#0d0e13"
foreground = "#a9b1d6"
black = "#12131b"
red = "#cea1ae"
green = "#b4cea1"
yellow = "#f9e2af"
blue = "#8a9cc2"
magenta = "#c55484"
cyan = "#55c0e3"
white = "${white}"
bright_black = "${black_bright}"
bright_red = "${red_bright}"
bright_green = "${green_bright}"
bright_yellow = "${yellow_bright}"
bright_blue = "${blue_bright}"
bright_magenta = "${magenta_bright}"
bright_cyan = "${cyan_bright}"
bright_white = "${white_bright}"
