attribute = { fg = "#8a9cc2" }
comment = { fg = "#565f89", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#f9e2af" }
constant = { fg = "#f38ba8" }
"constant.builtin" = { fg = "#a38ac2" }
"constant.builtin.boolean" = { fg = "#f38ba8" }
"constant.character" = { fg = "#b4cea1" }
"constant.character.escape" = { fg = "#f38ba8" }
"constant.numeric" = { fg = "#f38ba8" }
"constant.numeric.float" = { fg = "#f38ba8" }
"constant.numeric.integer" = { fg = "#f38ba8" }
constructor = { fg = "#8a9cc2" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { bg = "#323d5a", fg = "#7aa2f7" }
"diff.delta.moved" = { fg = "#8a9cc2" }
"diff.minus" = { bg = "#503747", fg = "#f38ba8" }
"diff.plus" = { bg = "#414845", fg = "#b4cea1" }
error = { fg = "#f38ba8" }
function = { fg = "#cea1ae", modifiers = ["italic"] }
"function.builtin" = { fg = "#a38ac2", modifiers = ["italic"] }
"function.macro" = { fg = "#8a9cc2", modifiers = ["italic"] }
"function.method" = { fg = "#cea1ae", modifiers = ["italic"] }
"function.special" = { fg = "#8a9cc2" }
hint = { fg = "#b4cea1" }
info = { fg = "#7aa2f7" }
keyword = { fg = "#a38ac2" }
"keyword.control" = { fg = "#f38ba8" }
"keyword.control.conditional" = { fg = "#a38ac2" }
"keyword.control.exception" = { fg = "#f38ba8" }
"keyword.control.repeat" = { fg = "#f38ba8" }
"keyword.control.return" = { fg = "#a38ac2" }
"keyword.directive" = { fg = "#8a9cc2" }
"keyword.function" = { fg = "#a38ac2" }
"keyword.operator" = { fg = "#f38ba8" }
label = { fg = "#8a9cc2" }
"markup.bold" = { fg = "#c0caf5", modifiers = ["bold"] }
"markup.heading" = { fg = "#8a9cc2" }
"markup.heading.completion" = { bg = "#0d0e13", fg = "#c0caf5" }
"markup.heading.hover" = { bg = "#343a55" }
"markup.italic" = { fg = "#c0caf5", modifiers = ["italic"] }
"markup.link" = { fg = "#7aa2f7" }
"markup.link.label" = { fg = "#7aa2f7" }
"markup.link.text" = { fg = "#7aa2f7" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#8a9cc2" }
"markup.normal.completion" = { fg = "#565f89" }
"markup.normal.hover" = { fg = "#8a9cc2" }
"markup.raw" = { fg = "#e5b799" }
"markup.raw.inline" = { bg = "#414868", fg = "#8a9cc2" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#8a9cc2" }
operator = { fg = "#f38ba8" }
special = { fg = "#7aa2f7" }
string = { fg = "#e5b799" }
"string.regexp" = { fg = "#7aa2f7" }
"string.special" = { fg = "#7aa2f7" }
tag = { fg = "#f38ba8" }
type = { fg = "#8a9cc2" }
"type.builtin" = { fg = "#a38ac2" }
"type.enum" = { fg = "#8a9cc2" }
"type.enum.variant" = { fg = "#f38ba8" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#c0caf5", fg = "#1a1b26" }
"ui.cursor.match" = { fg = "#e5b799", modifiers = ["bold"] }
"ui.linenr" = { fg = "#3b4261" }
"ui.linenr.select" = { fg = "#3b4261" }
"ui.menu" = { bg = "#0d0e13", fg = "#c0caf5" }
"ui.menu.scroll" = { bg = 1447710, fg = 3883617 }
"ui.menu.selected" = { bg = "#343a55" }
"ui.popup" = { bg = "#0d0e13", fg = "#3b4261" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#1a1b26", fg = "#a9b1d6" }
"ui.statusline.inactive" = { bg = "#1a1b26", fg = "#3b4261" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#1a1b26", fg = "#c0caf5" }
"ui.text.focus" = { bg = "#283457" }
"ui.text.inactive" = { fg = "#565f89", modifiers = ["italic"] }
"ui.text.info" = { bg = "#0d0e13", fg = "#8a9cc2" }
"ui.virtual.inlay-hint" = { bg = "#292d32", fg = "#b4cea1" }
"ui.window" = { fg = "#12131b", modifiers = ["bold"] }
variable = { fg = "#cea1ae" }
"variable.builtin" = { fg = "#a38ac2" }
"variable.other.member" = { fg = "#cea1ae" }
"variable.parameter" = { fg = "#cea1ae" }
warning = { fg = "#e5b799" }

[palette]
bg_float = "#0d0e13"
bg_popup = "#0d0e13"
bg_search = "#3d59a1"
bg_sidebar = "#0d0e13"
bg_statusline = "#1a1b26"
bg_visual = "#283457"
black = "#12131b"
border = "#12131b"
border_highlight = "#3b4261"
character = "#b4cea1"
code = "#cea1ae"
constant = "#f38ba8"
"diff.add" = "#414845"
"diff.change" = "#323d5a"
"diff.delete" = "#503747"
"diff.text" = "#394b70"
error = "#f38ba8"
fg_float = "#c0caf5"
fg_sidebar = "#a9b1d6"
"git.add" = "#b4cea1"
"git.change" = "#7aa2f7"
"git.delete" = "#f38ba8"
"git.ignore" = "#414868"
highlight = "#e5b799"
hint = "#b4cea1"
info = "#7aa2f7"
keyword = "#a38ac2"
match = "#7aa2f7"
operator = "#f38ba8"
rainbow = "#7aa2f7"
"rainbow.2" = "#f9e2af"
"rainbow.3" = "#b4cea1"
"rainbow.4" = "#55c0e3"
"rainbow.5" = "#c55484"
"rainbow.6" = "#a38ac2"
"rainbow.7" = "#e5b799"
"rainbow.8" = "#f38ba8"
special = "#7aa2f7"
statement = "#f38ba8"
string = "#e5b799"
"terminal.black" = "#12131b"
"terminal.black_bright" = "#414868"
"terminal.blue" = "#7aa2f7"
"terminal.blue_bright" = "#8db0ff"
"terminal.cyan" = "#55c0e3"
"terminal.cyan_bright" = "#00d2ff"
"terminal.green" = "#b4cea1"
"terminal.green_bright" = "#b5e191"
"terminal.magenta" = "#a38ac2"
"terminal.magenta_bright" = "#b594dc"
"terminal.red" = "#f38ba8"
"terminal.red_bright" = "#ff9ab6"
"terminal.white" = "#a9b1d6"
"terminal.white_bright" = "#c0caf5"
"terminal.yellow" = "#f9e2af"
"terminal.yellow_bright" = "#fef1d7"
title_popup = "#8a9cc2"
todo = "#7aa2f7"
type = "#8a9cc2"
visual = "#3d59a1"
warning = "#e5b799"