[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#a9b1d6", italic = true }

# Hovered
hovered         = { bg = "#292e42" }
preview_hovered = { bg = "#292e42" }

# Find
find_keyword  = { fg = "#0e0e16", bg = "#e5b799", bold = true }
find_position = { fg = "#89ddff", bg = "#24293b", bold = true }

# Marker
marker_copied   = { fg = "#addad7", bg = "#addad7" }
marker_cut      = { fg = "#f38ba8", bg = "#f38ba8" }
marker_marked   = { fg = "#cba6f7", bg = "#cba6f7" }
marker_selected = { fg = "#8a9cc2", bg = "#8a9cc2" }

# Tab
tab_active   = { fg = "#c0caf5", bg = "#292e42" }
tab_inactive = { fg = "#3b4261", bg = "#1a1b26" }
tab_width    = 1

# Count
count_copied   = { fg = "#c0caf5", bg = "#71a5b5" }
count_cut      = { fg = "#c0caf5", bg = "#eba0ac" }
count_selected = { fg = "#c0caf5", bg = "#3d59a1" }

# Border
border_symbol = "│"
border_style  = { fg = "#3b4261" }

[mode]
normal_main = { fg = "#12131b", bg = "#8a9cc2", bold = true }
normal_alt  = { fg = "#8a9cc2", bg = "#3b4261" }

select_main = { fg = "#12131b", bg = "#cba6f7", bold = true }
select_alt  = { fg = "#cba6f7", bg = "#3b4261" }

unset_main  = { fg = "#12131b", bg = "#a38ac2", bold = true }
unset_alt   = { fg = "#a38ac2", bg = "#3b4261" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#3b4261", bg = "#3b4261" }

# Progress
progress_label  = { fg = "#a9b1d6", bold = true }
progress_normal = { fg = "#1a1b26" }
progress_error  = { fg = "#f38ba8" }

# Permissions
perm_type  = { fg = "#8a9cc2" }
perm_read  = { fg = "#f9e2af" }
perm_write = { fg = "#f38ba8" }
perm_exec  = { fg = "#b4cea1" }
perm_sep   = { fg = "#414868" }

[pick]
border   = { fg = "#3b4261" }
active   = { fg = "#c0caf5",  bg = "#283457" }
inactive = { fg = "#c0caf5" }

# Input
[input]
border   = { fg = "#89ddff" }
title    = { fg = "#89ddff" }
value    = { fg = "#a38ac2" }
selected = { bg = "#283457" }

# Completion
[completion]
border   = { fg = "#89ddff" }
active   = { fg = "#c0caf5", bg = "#283457" }
inactive = { fg = "#c0caf5" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#3b4261" }
title   = { fg = "#3b4261" }
hovered = { fg = "#c0caf5", bg="#283457" }

# Which
[which]
cols            = 3
mask            = { bg = "#0e0e16" }
cand            = { fg = "#7dcfff" }
rest            = { fg = "#8a9cc2" }
desc            = { fg = "#cba6f7" }
separator       = " ➜ "
separator_style = { fg = "#565f89" }

# Confirm
[confirm]
border  = { fg = "#89ddff" }
title   = { fg = "#3b4261" }
content = {}
list    = {}
btn_yes = { bg = "#283457" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#3b4261" }
title   = { fg = "#3b4261" }

# Notify
[notify]
title_info  = { fg = "#7aa2f7" }
title_warn  = { fg = "#e5b799" }
title_error = { fg = "#f38ba8" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#b4cea1" }
run     = { fg = "#cba6f7" }
hovered = { bg = "#292e42" }
footer  = { fg = "#c0caf5", bg = "#1a1b26" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#f9e2af" },

	# Media
	{ mime = "{audio,video}/*", fg = "#cba6f7" },

	# Archives
	{ mime = "application/*zip", fg = "#f38ba8" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f38ba8" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7dcfff" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#f38ba8" },

	# Special files
	{ name = "*", is = "orphan", bg = "#f38ba8" },
	{ name = "*", is = "exec"  , fg = "#b4cea1" },

	# Fallback
	{ name = "*/", fg = "#8a9cc2" }
]
    